name: Node.js CI

on:
  push:
    branches:
      - main

env: 
  DATABSE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the desired Node.js version

    - name: Install Dependencies
      run: npm install

    - name: TypeScript Type Checking
      run: npm run type-check  # Replace 'type-check' with your TypeScript script name

    - name: Linting
      run: npm run lint  # Replace 'lint' with your linting script name
